import type { Metadata } from "next";
import Header from "@/components/header";
import { robotoFlex, robotoMono, inter } from '../fonts'
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
      className={`${robotoFlex.variable} ${robotoMono.variable} ${inter.variable}`}
      >
        <div className="container">
          <Header />
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
